service: open-book
app: open-book
org: franklx2

custom:
  bucket: open-book-pages

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

#  stage: dev
#  region: us-east-1

functions:
  hello:
    handler: handler.hello
    environment:
      bucketName: ${self:custom.bucket}
    events:
      - http:
          path: hello
          method: post
resources:
 Resources:
   PagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
 Outputs:
    PagesBucket:
      Description: "Description for the output"
      Value: 
        Ref: PagesBucket